/* Generated By:JJTree: Do not edit this line. ASTLambdaExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLambdaExpr extends SimpleNode {
	
	
  public ASTLambdaExpr(int id) {
    super(id);
  }

  public ASTLambdaExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public SimpleNode interpret() {
	  
	return null;
  }
}
/* JavaCC - OriginalChecksum=0ca18491d57e41efe91764643e88f533 (do not edit this line) */
