/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NIL = 6;
  /** RegularExpression Id. */
  int LPAR = 7;
  /** RegularExpression Id. */
  int RPAR = 8;
  /** RegularExpression Id. */
  int TICK = 9;
  /** RegularExpression Id. */
  int INTEGER = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int LAMBDA = 12;
  /** RegularExpression Id. */
  int LET = 13;
  /** RegularExpression Id. */
  int LETREC = 14;
  /** RegularExpression Id. */
  int ADD_OP = 15;
  /** RegularExpression Id. */
  int SUB_OP = 16;
  /** RegularExpression Id. */
  int CAR = 17;
  /** RegularExpression Id. */
  int CDR = 18;
  /** RegularExpression Id. */
  int CONS = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int ERROR = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<NIL>",
    "\"(\"",
    "\")\"",
    "\"\\\'\"",
    "<INTEGER>",
    "<FLOAT>",
    "<LAMBDA>",
    "\"let\"",
    "\"letrec\"",
    "\"+\"",
    "\"-\"",
    "\"car\"",
    "\"cdr\"",
    "\"cons\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<ERROR>",
  };

}
