/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTLISPNODE = 0;
  public int JJTLIST = 1;
  public int JJTATOM = 2;
  public int JJTCAR = 3;
  public int JJTCDR = 4;
  public int JJTCONS = 5;
  public int JJTADDEXPR = 6;
  public int JJTSUBEXPR = 7;
  public int JJTLETEXPR = 8;
  public int JJTLAMBDAEXPR = 9;


  public String[] jjtNodeName = {
    "LispNode",
    "List",
    "Atom",
    "car",
    "cdr",
    "cons",
    "AddExpr",
    "SubExpr",
    "LetExpr",
    "LambdaExpr",
  };
}
/* JavaCC - OriginalChecksum=72ba3a796d3f9cf56f9ec8d1836a5612 (do not edit this line) */
