/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTLispNode node, Object data);
  public Object visit(ASTList node, Object data);
  public Object visit(ASTAtom node, Object data);
  public Object visit(ASTcar node, Object data);
  public Object visit(ASTcdr node, Object data);
  public Object visit(ASTcons node, Object data);
  public Object visit(ASTAddExpr node, Object data);
  public Object visit(ASTSubExpr node, Object data);
  public Object visit(ASTLetExpr node, Object data);
  public Object visit(ASTLambdaExpr node, Object data);
}
/* JavaCC - OriginalChecksum=98f225c9774a8e35fac71152d0f7d617 (do not edit this line) */
